'use client';

import { useState, useCallback, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles,
  RotateCcw,
  ArrowRight,
  Linkedin,
  Facebook,
  Instagram,
  Twitter,
  Hash,
  Clock,
  TrendingUp,
  Shuffle,
  Check,
  type LucideIcon,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  demoTemplates,
  getDemoContent,
  getRandomDemoContent,
  type DemoTemplate,
  type DemoContent,
} from '@/data/demo-content';

const randomTopics: readonly string[] = [
  'Plumbing contractor',
  'HVAC company',
  'Roofing business',
  'Landscaping company',
  'Real estate agent',
  'Restaurant owner',
  'Fitness studio',
  'Dental practice',
  'Law firm',
  'Cleaning service',
] as const;

interface PlatformOption {
  id: string;
  name: string;
  icon: LucideIcon;
  color: string;
}

const platforms: readonly PlatformOption[] = [
  { id: 'linkedin', name: 'LinkedIn', icon: Linkedin, color: 'bg-blue-600' },
  { id: 'facebook', name: 'Facebook', icon: Facebook, color: 'bg-blue-500' },
  { id: 'instagram', name: 'Instagram', icon: Instagram, color: 'bg-pink-500' },
  { id: 'twitter', name: 'Twitter/X', icon: Twitter, color: 'bg-sky-500' },
] as const;

const fadeInUp = {
  initial: { opacity: 0, y: 16 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -8 },
  transition: { duration: 0.35, ease: 'easeOut' as const },
};

function StepBadge({ number, label }: { number: number; label: string }) {
  return (
    <div className="flex items-center gap-2 mb-4">
      <span className="flex items-center justify-center w-7 h-7 rounded-full bg-orange-500 text-white text-sm font-bold">
        {number}
      </span>
      <span className="text-sm font-semibold text-slate-300 uppercase tracking-wide">
        {label}
      </span>
    </div>
  );
}

function TypingAnimation() {
  return (
    <div className="flex items-center justify-center gap-3 py-16">
      <div className="flex items-center gap-2">
        <Sparkles className="h-5 w-5 text-orange-500 animate-pulse" />
        <span className="text-slate-300 font-medium">
          AI is generating your content
        </span>
      </div>
      <div className="flex gap-1">
        {[0, 1, 2].map((i) => (
          <motion.div
            key={i}
            className="w-2 h-2 rounded-full bg-orange-500"
            animate={{ y: [0, -8, 0] }}
            transition={{
              duration: 0.6,
              repeat: Infinity,
              delay: i * 0.15,
              ease: 'easeInOut',
            }}
          />
        ))}
      </div>
    </div>
  );
}

function PlatformBadge({ platform }: { platform: string }) {
  const match = platforms.find((p) => p.id === platform);
  if (!match) return null;
  const Icon = match.icon;
  return (
    <span
      className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold text-white ${match.color}`}
    >
      <Icon className="h-3.5 w-3.5" />
      {match.name}
    </span>
  );
}

function GeneratedResult({
  content,
  onRegenerate,
  onReset,
}: {
  content: DemoContent;
  onRegenerate: () => void;
  onReset: () => void;
}) {
  return (
    <motion.div {...fadeInUp} className="space-y-4">
      {/* Result card */}
      <div className="rounded-xl border border-slate-700/50 bg-slate-800/50 overflow-hidden">
        {/* Card header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-slate-700/50 bg-slate-800/80">
          <PlatformBadge platform={content.platform} />
          <span className="text-xs text-slate-500">
            Generated by KontentFire AI
          </span>
        </div>

        {/* Card body */}
        <div className="px-5 py-5 space-y-4">
          <h3 className="text-lg font-bold text-white leading-snug">
            {content.generatedTitle}
          </h3>
          <div className="text-sm text-slate-300 leading-relaxed whitespace-pre-line">
            {content.generatedContent}
          </div>

          {/* Hashtags */}
          <div className="flex flex-wrap gap-2 pt-1">
            <Hash className="h-4 w-4 text-orange-500/70 mt-0.5" />
            {content.hashtags.map((tag) => (
              <span
                key={tag}
                className="text-xs font-medium text-orange-400 bg-orange-500/10 px-2 py-1 rounded-md"
              >
                {tag}
              </span>
            ))}
          </div>

          {/* Schedule suggestion */}
          <div className="flex items-start gap-2 p-3 rounded-lg bg-slate-900/50 border border-slate-700/30">
            <Clock className="h-4 w-4 text-blue-400 mt-0.5 shrink-0" />
            <div>
              <p className="text-xs font-semibold text-blue-400 mb-0.5">
                Best Time to Post
              </p>
              <p className="text-xs text-slate-400">
                {content.scheduleSuggestion}
              </p>
            </div>
          </div>

          {/* Engagement tip */}
          <div className="flex items-start gap-2 p-3 rounded-lg bg-slate-900/50 border border-slate-700/30">
            <TrendingUp className="h-4 w-4 text-green-400 mt-0.5 shrink-0" />
            <div>
              <p className="text-xs font-semibold text-green-400 mb-0.5">
                Engagement Tip
              </p>
              <p className="text-xs text-slate-400">
                {content.engagementTip}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Action buttons */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
        <Button
          variant="outline"
          size="sm"
          onClick={onRegenerate}
          className="flex-1"
        >
          <RotateCcw className="mr-2 h-4 w-4" />
          Regenerate
        </Button>
        <a
          href="https://app.kontentfire.com/login"
          target="_blank"
          rel="noopener noreferrer"
          className="flex-1"
        >
          <Button size="sm" className="w-full group">
            Create Real Content
            <ArrowRight className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" />
          </Button>
        </a>
      </div>

      {/* Start over */}
      <div className="text-center pt-2">
        <button
          onClick={onReset}
          className="text-xs text-slate-500 hover:text-slate-300 transition-colors underline underline-offset-2"
        >
          Start Over
        </button>
      </div>
    </motion.div>
  );
}

export function InteractiveDemo() {
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);
  const [topic, setTopic] = useState('');
  const [selectedPlatform, setSelectedPlatform] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedContent, setGeneratedContent] = useState<DemoContent | null>(
    null
  );

  const activeTemplate = useMemo(
    () => demoTemplates.find((t) => t.id === selectedTemplate) ?? null,
    [selectedTemplate]
  );

  const handleSelectTemplate = useCallback((templateId: string) => {
    setSelectedTemplate(templateId);
    setSelectedPlatform(null);
    setGeneratedContent(null);
    setIsGenerating(false);
  }, []);

  const handleSurpriseMe = useCallback(() => {
    const randomTopic = randomTopics[Math.floor(Math.random() * randomTopics.length)];
    setTopic(randomTopic);
  }, []);

  const handleSelectPlatform = useCallback((platformId: string) => {
    setSelectedPlatform(platformId);
    setGeneratedContent(null);
    setIsGenerating(false);
  }, []);

  const handleGenerate = useCallback(() => {
    if (!selectedTemplate || !selectedPlatform) return;

    setIsGenerating(true);
    setGeneratedContent(null);

    const delay = 2000 + Math.random() * 1000;

    setTimeout(() => {
      const matches = getDemoContent(selectedTemplate, selectedPlatform);
      const content = matches.length > 0
        ? matches[Math.floor(Math.random() * matches.length)]
        : getRandomDemoContent(selectedTemplate, selectedPlatform);
      setGeneratedContent(content);
      setIsGenerating(false);
    }, delay);
  }, [selectedTemplate, selectedPlatform]);

  const handleRegenerate = useCallback(() => {
    setIsGenerating(true);
    setGeneratedContent(null);

    setTimeout(() => {
      setGeneratedContent(getRandomDemoContent());
      setIsGenerating(false);
    }, 1500);
  }, []);

  const handleReset = useCallback(() => {
    setSelectedTemplate(null);
    setTopic('');
    setSelectedPlatform(null);
    setIsGenerating(false);
    setGeneratedContent(null);
  }, []);

  const currentStep = useMemo(() => {
    if (generatedContent) return 5;
    if (isGenerating) return 4;
    if (selectedPlatform) return 4;
    if (selectedTemplate) return 2;
    return 1;
  }, [selectedTemplate, selectedPlatform, isGenerating, generatedContent]);

  return (
    <div className="w-full max-w-3xl mx-auto">
      <div className="rounded-2xl border border-slate-700/50 bg-slate-900/80 backdrop-blur-sm overflow-hidden shadow-2xl shadow-orange-500/5">
        {/* Header */}
        <div className="px-5 py-4 border-b border-slate-700/50 bg-slate-800/50 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-orange-500" />
            <h3 className="font-bold text-white">AI Content Generator</h3>
          </div>
          {currentStep > 1 && (
            <button
              onClick={handleReset}
              className="text-xs text-slate-500 hover:text-slate-300 transition-colors flex items-center gap-1"
            >
              <RotateCcw className="h-3 w-3" />
              Start Over
            </button>
          )}
        </div>

        <div className="p-5 space-y-6">
          {/* Step 1: Choose Template */}
          <div>
            <StepBadge number={1} label="Choose a Template" />
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
              {demoTemplates.map((template: DemoTemplate) => {
                const isSelected = selectedTemplate === template.id;
                return (
                  <motion.button
                    key={template.id}
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => handleSelectTemplate(template.id)}
                    className={`relative p-3 rounded-lg border text-left transition-colors ${
                      isSelected
                        ? 'border-orange-500 bg-orange-500/10'
                        : 'border-slate-700/50 bg-slate-800/50 hover:border-slate-600'
                    }`}
                  >
                    {isSelected && (
                      <div className="absolute top-2 right-2">
                        <Check className="h-3.5 w-3.5 text-orange-500" />
                      </div>
                    )}
                    <span className="text-lg mb-1.5 block" role="img" aria-label={template.name}>
                      {template.icon}
                    </span>
                    <p
                      className={`text-sm font-semibold ${
                        isSelected ? 'text-white' : 'text-slate-200'
                      }`}
                    >
                      {template.name}
                    </p>
                    <p className="text-xs text-slate-500 mt-0.5 line-clamp-2">
                      {template.description}
                    </p>
                  </motion.button>
                );
              })}
            </div>
          </div>

          {/* Step 2: Enter Topic */}
          <AnimatePresence mode="wait">
            {currentStep >= 2 && !generatedContent && !isGenerating && (
              <motion.div {...fadeInUp} key="step-2">
                <StepBadge number={2} label="Enter Your Topic" />
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder={
                      activeTemplate?.example
                        ? `e.g. ${activeTemplate.example.replace(/"/g, '')}`
                        : 'e.g. Plumbing contractor'
                    }
                    className="flex-1 px-4 py-2.5 rounded-lg bg-slate-800 border border-slate-700/50 text-sm text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-orange-500/50 focus:border-orange-500/50 transition-colors"
                  />
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleSurpriseMe}
                    className="shrink-0 text-slate-400 hover:text-orange-400"
                  >
                    <Shuffle className="h-4 w-4 mr-1.5" />
                    Surprise Me
                  </Button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Step 3: Choose Platform */}
          <AnimatePresence mode="wait">
            {currentStep >= 2 && !generatedContent && !isGenerating && (
              <motion.div {...fadeInUp} key="step-3">
                <StepBadge number={3} label="Choose Platform" />
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
                  {platforms.map((platform) => {
                    const Icon = platform.icon;
                    const isSelected = selectedPlatform === platform.id;
                    return (
                      <motion.button
                        key={platform.id}
                        whileHover={{ scale: 1.03 }}
                        whileTap={{ scale: 0.97 }}
                        onClick={() => handleSelectPlatform(platform.id)}
                        className={`flex items-center gap-2 p-3 rounded-lg border text-left transition-colors ${
                          isSelected
                            ? 'border-orange-500 bg-orange-500/10'
                            : 'border-slate-700/50 bg-slate-800/50 hover:border-slate-600'
                        }`}
                      >
                        <div
                          className={`p-1.5 rounded-md ${
                            isSelected ? platform.color : 'bg-slate-700'
                          }`}
                        >
                          <Icon className="h-4 w-4 text-white" />
                        </div>
                        <span
                          className={`text-sm font-medium ${
                            isSelected ? 'text-white' : 'text-slate-300'
                          }`}
                        >
                          {platform.name}
                        </span>
                      </motion.button>
                    );
                  })}
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Step 4: Generate */}
          <AnimatePresence mode="wait">
            {selectedPlatform && !generatedContent && !isGenerating && (
              <motion.div {...fadeInUp} key="step-4">
                <StepBadge number={4} label="Generate" />
                <Button
                  size="lg"
                  onClick={handleGenerate}
                  className="w-full group"
                >
                  <Sparkles className="mr-2 h-5 w-5" />
                  Generate Content
                  <ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
                </Button>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Generating animation */}
          <AnimatePresence mode="wait">
            {isGenerating && (
              <motion.div {...fadeInUp} key="generating">
                <TypingAnimation />
              </motion.div>
            )}
          </AnimatePresence>

          {/* Generated result */}
          <AnimatePresence mode="wait">
            {generatedContent && !isGenerating && (
              <GeneratedResult
                key="result"
                content={generatedContent}
                onRegenerate={handleRegenerate}
                onReset={handleReset}
              />
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
