'use client';

import Image from 'next/image';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { ArrowRight } from 'lucide-react';

interface MockupPost {
  src: string;
  alt: string;
  platform: string;
  badgeColor: string;
}

const posts: readonly MockupPost[] = [
  {
    src: '/mockups/linkedin-post-2.png',
    alt: 'AI-generated LinkedIn post about marketing automation',
    platform: 'LinkedIn',
    badgeColor: 'bg-blue-600 text-white',
  },
  {
    src: '/mockups/instagram-post-2.png',
    alt: 'AI-generated Instagram post for landscaping business',
    platform: 'Instagram',
    badgeColor: 'bg-gradient-to-r from-purple-500 to-pink-500 text-white',
  },
  {
    src: '/mockups/facebook-post-1.png',
    alt: 'AI-generated Facebook post for HVAC company',
    platform: 'Facebook',
    badgeColor: 'bg-blue-500 text-white',
  },
  {
    src: '/mockups/twitter-post-1.png',
    alt: 'AI-generated Twitter post with analytics data',
    platform: 'Twitter',
    badgeColor: 'bg-slate-900 text-white',
  },
] as const;

const cardVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.15, duration: 0.5, ease: 'easeOut' as const },
  }),
};

export function SocialProofShowcase() {
  return (
    <section className="py-20 bg-slate-50 dark:bg-slate-800/50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-4">
            See What KontentFire Creates
          </h2>
          <p className="text-lg text-slate-600 dark:text-slate-300 max-w-2xl mx-auto">
            Real examples of AI-generated social media posts across every major platform.
          </p>
        </div>

        <div className="grid sm:grid-cols-2 gap-6 max-w-5xl mx-auto">
          {posts.map((post, i) => (
            <motion.div
              key={post.platform}
              custom={i}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, margin: '-50px' }}
              variants={cardVariants}
              whileHover={{ scale: 1.03 }}
              transition={{ type: 'spring', stiffness: 300, damping: 20 }}
              className="relative rounded-2xl overflow-hidden shadow-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900"
            >
              <div className="absolute top-3 left-3 z-10">
                <span
                  className={`inline-block px-3 py-1 rounded-full text-xs font-semibold ${post.badgeColor}`}
                >
                  {post.platform}
                </span>
              </div>
              <Image
                src={post.src}
                alt={post.alt}
                width={600}
                height={600}
                className="w-full h-auto"
              />
            </motion.div>
          ))}
        </div>

        <div className="text-center mt-12">
          <p className="text-lg text-slate-600 dark:text-slate-300 mb-6">
            All generated by AI in seconds. Real posts, real engagement.
          </p>
          <Link href="/free-trial">
            <Button size="lg">
              Start Your Free Trial <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </Link>
        </div>
      </div>
    </section>
  );
}
